from .auth import router as auth_router
from .users import router as users_router
from .categories import router as categories_router
from .stages import router as stages_router
from .suppliers import router as suppliers_router
from .purchase_requests import router as purchase_requests_router
from .rfqs import router as rfqs_router
from .quotes import router as quotes_router
from .orders import router as orders_router
from .dashboard import router as dashboard_router
